-- 코드를 입력하세요
WITH TOTAL_SALES_JANUARY AS (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
    FROM BOOK_SALES 
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE < '2022-02-01'
    GROUP BY BOOK_ID
)

SELECT
    A.AUTHOR_ID, 
    A.AUTHOR_NAME, 
    B.CATEGORY,
    SUM(B.PRICE * TSJ.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK B 
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN TOTAL_SALES_JANUARY TSJ ON B.BOOK_ID = TSJ.BOOK_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
;