SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  AND D.DURATION_TYPE = '30일 이상'
  -- 11월 중 대여 이력이 없는 차량만
  AND C.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE NOT (
          END_DATE < '2022-11-01' OR START_DATE > '2022-11-30'
      )
  )
  -- 금액 조건
  AND (C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) >= 500000
  AND (C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;
