-- GROUP BY
SELECT CAR_ID,
       CASE 
         WHEN MAX(CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1 ELSE 0 END) = 1 
         THEN '대여중'
         ELSE '대여 가능'
       END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;



-- JOIN & GROUP BY
# WITH CAR_RENTING_OCT_SIXTEEN AS (
#     SELECT *
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
#     # WHERE START_DATE <= '2022-10-16'
#     #     AND END_DATE >= '2022-10-16'
#     WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
# )
        
# SELECT CH.CAR_ID, 
#     CASE WHEN COUNT(COS.CAR_ID) > 0 THEN '대여중'
#     ELSE '대여 가능'
#     END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
#     LEFT JOIN CAR_RENTING_OCT_SIXTEEN COS
#     ON CH.CAR_ID = COS.CAR_ID
# GROUP BY CH.CAR_ID
# ORDER BY CH.CAR_ID DESC 
# ;

-- 서브쿼리
SELECT 
  C.CAR_ID,
  CASE 
    WHEN EXISTS (
      SELECT 1
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE CAR_ID = C.CAR_ID
        AND '2022-10-16' BETWEEN START_DATE AND END_DATE
    )
    THEN '대여중'
    ELSE '대여 가능'
  END AS AVAILABILITY
FROM (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) C
ORDER BY C.CAR_ID DESC;