-- 코드를 입력하세요
WITH CAR_RENTING_OCT_SIXTEEN AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
    WHERE START_DATE <= '2022-10-16'
        AND END_DATE >= '2022-10-16'
)

# SELECT DISTINCT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
# WHERE START_DATE <= '2022-10-16'
#     AND END_DATE >= '2022-10-16'
        
SELECT CH.CAR_ID, 
    CASE WHEN COUNT(COS.CAR_ID) > 0 THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CH
    LEFT JOIN CAR_RENTING_OCT_SIXTEEN COS
    ON CH.HISTORY_ID = COS.HISTORY_ID
GROUP BY CH.CAR_ID
ORDER BY CH.CAR_ID DESC 
;