# -- 코드를 작성해주세요
SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
WHERE D.SKILL_CODE & (SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE LOWER(CATEGORY) LIKE 'front%') > 0
ORDER BY D.ID
;

# SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME, D.SKILL_CODE
# FROM DEVELOPERS D
# WHERE D.SKILL_CODE & 16 > 0
#     OR D.SKILL_CODE & 2048 > 0
#     OR D.SKILL_CODE & 8192 > 0

-- 그냥 SELECT CODE하면 '실패 (1242, 'Subquery returns more than 1 row')' 뜸