-- 코드를 입력하세요
SELECT UGU.USER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER UGU JOIN USED_GOODS_BOARD UGB ON UGU.USER_ID = UGB.WRITER_ID
WHERE UPPER(UGB.STATUS) = 'DONE'
GROUP BY UGU.USER_ID, UGU.NICKNAME
HAVING SUM(UGB.PRICE) >= 700000
ORDER BY TOTAL_SALES
;